repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: This hook runs flake8 within our project's environment.
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true